# Generated by Django 3.2.9 on 2021-11-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StarWarsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='saga',
        ),
    ]
