# Generated by Django 3.2.9 on 2021-11-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarWarsApp', '0002_remove_pelicula_saga'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='actor',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
